kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.hello-events-in.connector=smallrye-kafka
mp.messaging.incoming.hello-events-in.topic=hello-topic
mp.messaging.incoming.hello-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.incoming.commands-in.connector=smallrye-kafka
mp.messaging.incoming.commands-in.topic=commands-topic
mp.messaging.incoming.commands-in.value.deserializer=model.BusMessageDeserializer

mp.messaging.outgoing.replies-out.connector=smallrye-kafka
mp.messaging.outgoing.replies-out.topic=replies-topic

# Postgres
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/busdb?options=-c%20timezone=UTC
quarkus.hibernate-orm.schema-management.strategy=update

# Redis
quarkus.redis.hosts=redis://localhost:6379