quarkus.http.port=8081
quarkus.rest-client.beta.url=http://localhost:8080

kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.hello-events.connector=smallrye-kafka
mp.messaging.outgoing.hello-events.topic=hello-topic
mp.messaging.outgoing.hello-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.commands-out.connector=smallrye-kafka
mp.messaging.outgoing.commands-out.topic=commands-topic
mp.messaging.outgoing.commands-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.replies-in.connector=smallrye-kafka
mp.messaging.incoming.replies-in.topic=replies-topic
mp.messaging.incoming.replies-in.value.deserializer=model.BusMessageDeserializer